site_name: A2Bridge User Guide
theme:
  name: readthedocs

markdown_extensions:
  - attr_list
  - toc
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.superfences
  - pymdownx.emoji
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
