site_name: A2Bridge User Guide
theme:
  name: readthedocs

docs_dir: ./docs/userguide

markdown_extensions:
  - attr_list
  - toc
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.superfences
  - pymdownx.emoji
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - layout.css

nav:
  - index.md
  - setup.md
  - json.md
  - serial.md
  - dfu.md
