site_name: A2Bridge User Guide
theme:
  name: material
  palette:
    - scheme: default
      primary: blue

  features:
    - content.tabs.link
    - user_color_mode_toggle

docs_dir: ./docs/userguide

markdown_extensions:
  - attr_list
  - toc
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.superfences
  - pymdownx.emoji
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

extra_css:
  - layout.css

nav:
  - index.md
  - setup.md
  - json.md
  - serial.md
  - dfu.md
